# Data Configuration
data:
  raw_data_path: "data/raw/bike_train.csv"
  processed_data_path: "data/processed/bike_processed.csv"
  features_path: "data/processed/features/processed_features.csv"
  test_size: 0.2
  random_state: 42

# Feature Engineering Configuration
features:
  polynomial_degree: 2
  scaling: true
  cyclical_features:
    - name: "hour"
      period: 24
    - name: "month"
      period: 12
    - name: "dayofweek"
      period: 7

# Model Configuration
models:
  linear:
    - name: "Linear Regression"
      use_poly: true
    - name: "Ridge"
      use_poly: true
      params:
        alpha: [0.01, 0.1, 1.0, 10.0, 100.0]
    - name: "Lasso"
      use_poly: true
      params:
        alpha: [0.01, 0.1, 1.0, 10.0, 100.0]
  
  tree:
    - name: "Random Forest"
      params:
        n_estimators: [100, 200, 300, 400, 500]
        max_depth: [10, 20, 30, 40, 50]
        min_samples_split: [2, 5, 10, 15, 20]
        min_samples_leaf: [1, 2, 4, 6, 8]
    
    - name: "XGBoost"
      params:
        n_estimators: [100, 200, 300, 400, 500]
        max_depth: [3, 4, 5, 6, 7, 8, 9, 10]
        learning_rate: [0.01, 0.05, 0.1, 0.15, 0.2]
        subsample: [0.6, 0.7, 0.8, 0.9, 1.0]
        colsample_bytree: [0.6, 0.7, 0.8, 0.9, 1.0]

# Training Configuration
training:
  cv_folds: 5
  n_iter_random_search: 20
  metrics:
    - "rmse"
    - "r2_score"
  early_stopping_rounds: 10

# Logging Configuration
logging:
  level: "INFO"
  save_path: "logs"
  model_save_path: "models/saved"